name: Sync Fork with Upstream

# 需要写权限
permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 0点自动运行
  workflow_dispatch: # 允许手动触发
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Sync with upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: main
          upstream_sync_repo: Aur5411/TiebaApp
          upstream_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
